blank_issues_enabled: false
contact_links:
  - name: How To
    url: https://ddnexus.github.io/pagy/docs/how-to/
    about: Quick recipes to get what you want from pagy
  - name: Pagy Q&A Discussions
    url: https://github.com/ddnexus/pagy/discussions/categories/q-a
    about: Ask and answer questions here
  - name: Pagy Guru
    url: https://gurubase.io/g/pagy
    about: Ask and Pagy Guru will attempt to find an answer.
