#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"
root="$(git rev-parse --show-toplevel)"
jdir="$root/gem/javascripts"

echo 'Generating javascript files'

# 1. ESM Module (Native export from pagy.ts)
bun build --target=node --no-bundle --outfile=$jdir/pagy.mjs pagy.ts

# 2. Browser IIFE
bun build --target=browser --minify --outfile=$jdir/pagy.min.js pagy-shim.ts
sed -zi 's/;window\.Pagy=[^;]*;/;/; s/^[^=]*=/window.Pagy=/; ' $jdir/pagy.min.js  # remove extra var X pollution

# 3. Browser development/debug with sourcemap
bun build --target=browser --sourcemap=inline --outfile=$jdir/pagy.js pagy-shim.ts

# 4. Wand (Browser script)
bun build ./wand.ts --target=browser --no-bundle --outfile=$jdir/wand.js
