name: Publish Retype powered website to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - v6

jobs:
  publish:
    name: Publish to docs-site branch

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: retypeapp/action-build@v2

      - uses: retypeapp/action-github-pages@v2
        with:
          branch: docs-site
          update-branch: true
